export const metadata = {
  title: "Maktabty || Favourite Books",
  description: "Generated by Ather Elsawy",
};


export default function FavouriteBooksLayout({ children }) {
  return (
    <div>
      {children}
    </div>
  );
}