export const metadata = {
  title: "Maktabty || Login",
  description: "Generated by Ather Elsawy",
};


export default function LoginLayout({ children }) {
  return (
    <div>
      {children}
    </div>
  );
}