export const metadata = {
  title: "Maktabty || signup",
  description: "Generated by Ather Elsawy",
};

export default function SignUpLayout({ children }) {
  return (
    <div>
      {children}
    </div>
  );
}