export const metadata = {
  title: "Maktabty || All Books",
  description: "Generated by Ather Elsawy",
};

export default function BooksLayout({ children }) {
  return (
    <div>
      {children}
    </div>
  );
}