export const metadata = {
  title: "Maktabty || Daily Books",
  description: "Generated by Ather Elsawy",
};

export default function DailyBooksLayout({ children }) {
  return (
    <div>
      {children}
    </div>
  );
}